/* tslint:disable */
/* eslint-disable */
/**
 * User account and session management
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CreateOrUpdateOrganizationPayload,
    CreateOrUpdateOrganizationPayloadFromJSON,
    CreateOrUpdateOrganizationPayloadToJSON,
    CreateOrganizationPayload,
    CreateOrganizationPayloadFromJSON,
    CreateOrganizationPayloadToJSON,
    CreateRole,
    CreateRoleFromJSON,
    CreateRoleToJSON,
    ErrorPayload,
    ErrorPayloadFromJSON,
    ErrorPayloadToJSON,
    ListUserOrganizations,
    ListUserOrganizationsFromJSON,
    ListUserOrganizationsToJSON,
    Organization,
    OrganizationFromJSON,
    OrganizationToJSON,
    OrganizationCreated,
    OrganizationCreatedFromJSON,
    OrganizationCreatedToJSON,
    RoleCreated,
    RoleCreatedFromJSON,
    RoleCreatedToJSON,
} from '../models';

export interface CreateOrUpdateOrganizationRequest {
    uuid: string;
    createOrUpdateOrganizationPayload: CreateOrUpdateOrganizationPayload;
}

export interface CreateOrUpdateRoleRequest {
    uuid: string;
    roleId: string;
    createRole: CreateRole;
}

export interface CreateOrganizationRequest {
    createOrganizationPayload: CreateOrganizationPayload;
}

export interface CreateRoleRequest {
    uuid: string;
    createRole: CreateRole;
}

export interface GetOrganizationRequest {
    uuid: string;
    xUserUuid?: string;
}

export interface ListOrganizationRequest {
    max: number;
    pageToken?: string;
    parent?: string;
    xUserUuid?: string;
}

/**
 * 
 */
export class OrganizationApi extends runtime.BaseAPI {

    /**
     * Create or update an organization for a given uuid
     */
    async createOrUpdateOrganizationRaw(requestParameters: CreateOrUpdateOrganizationRequest): Promise<runtime.ApiResponse<OrganizationCreated>> {
        if (requestParameters.uuid === null || requestParameters.uuid === undefined) {
            throw new runtime.RequiredError('uuid','Required parameter requestParameters.uuid was null or undefined when calling createOrUpdateOrganization.');
        }

        if (requestParameters.createOrUpdateOrganizationPayload === null || requestParameters.createOrUpdateOrganizationPayload === undefined) {
            throw new runtime.RequiredError('createOrUpdateOrganizationPayload','Required parameter requestParameters.createOrUpdateOrganizationPayload was null or undefined when calling createOrUpdateOrganization.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/organizations/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters.uuid))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CreateOrUpdateOrganizationPayloadToJSON(requestParameters.createOrUpdateOrganizationPayload),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationCreatedFromJSON(jsonValue));
    }

    /**
     * Create or update an organization for a given uuid
     */
    async createOrUpdateOrganization(requestParameters: CreateOrUpdateOrganizationRequest): Promise<OrganizationCreated> {
        const response = await this.createOrUpdateOrganizationRaw(requestParameters);
        return await response.value();
    }

    /**
     * Create or update organization roles for a given uuid
     */
    async createOrUpdateRoleRaw(requestParameters: CreateOrUpdateRoleRequest): Promise<runtime.ApiResponse<RoleCreated>> {
        if (requestParameters.uuid === null || requestParameters.uuid === undefined) {
            throw new runtime.RequiredError('uuid','Required parameter requestParameters.uuid was null or undefined when calling createOrUpdateRole.');
        }

        if (requestParameters.roleId === null || requestParameters.roleId === undefined) {
            throw new runtime.RequiredError('roleId','Required parameter requestParameters.roleId was null or undefined when calling createOrUpdateRole.');
        }

        if (requestParameters.createRole === null || requestParameters.createRole === undefined) {
            throw new runtime.RequiredError('createRole','Required parameter requestParameters.createRole was null or undefined when calling createOrUpdateRole.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/organizations/{uuid}/roles/{roleId}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters.uuid))).replace(`{${"roleId"}}`, encodeURIComponent(String(requestParameters.roleId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CreateRoleToJSON(requestParameters.createRole),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => RoleCreatedFromJSON(jsonValue));
    }

    /**
     * Create or update organization roles for a given uuid
     */
    async createOrUpdateRole(requestParameters: CreateOrUpdateRoleRequest): Promise<RoleCreated> {
        const response = await this.createOrUpdateRoleRaw(requestParameters);
        return await response.value();
    }

    /**
     * Creates a new organization
     */
    async createOrganizationRaw(requestParameters: CreateOrganizationRequest): Promise<runtime.ApiResponse<OrganizationCreated>> {
        if (requestParameters.createOrganizationPayload === null || requestParameters.createOrganizationPayload === undefined) {
            throw new runtime.RequiredError('createOrganizationPayload','Required parameter requestParameters.createOrganizationPayload was null or undefined when calling createOrganization.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/organizations`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateOrganizationPayloadToJSON(requestParameters.createOrganizationPayload),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationCreatedFromJSON(jsonValue));
    }

    /**
     * Creates a new organization
     */
    async createOrganization(requestParameters: CreateOrganizationRequest): Promise<OrganizationCreated> {
        const response = await this.createOrganizationRaw(requestParameters);
        return await response.value();
    }

    /**
     * Create organization roles for a given uuid
     */
    async createRoleRaw(requestParameters: CreateRoleRequest): Promise<runtime.ApiResponse<RoleCreated>> {
        if (requestParameters.uuid === null || requestParameters.uuid === undefined) {
            throw new runtime.RequiredError('uuid','Required parameter requestParameters.uuid was null or undefined when calling createRole.');
        }

        if (requestParameters.createRole === null || requestParameters.createRole === undefined) {
            throw new runtime.RequiredError('createRole','Required parameter requestParameters.createRole was null or undefined when calling createRole.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/organizations/{uuid}/roles`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters.uuid))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateRoleToJSON(requestParameters.createRole),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => RoleCreatedFromJSON(jsonValue));
    }

    /**
     * Create organization roles for a given uuid
     */
    async createRole(requestParameters: CreateRoleRequest): Promise<RoleCreated> {
        const response = await this.createRoleRaw(requestParameters);
        return await response.value();
    }

    /**
     * Get detailed information about an organization.
     */
    async getOrganizationRaw(requestParameters: GetOrganizationRequest): Promise<runtime.ApiResponse<Organization>> {
        if (requestParameters.uuid === null || requestParameters.uuid === undefined) {
            throw new runtime.RequiredError('uuid','Required parameter requestParameters.uuid was null or undefined when calling getOrganization.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xUserUuid !== undefined && requestParameters.xUserUuid !== null) {
            headerParameters['X-User-Uuid'] = String(requestParameters.xUserUuid);
        }

        const response = await this.request({
            path: `/organizations/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters.uuid))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationFromJSON(jsonValue));
    }

    /**
     * Get detailed information about an organization.
     */
    async getOrganization(requestParameters: GetOrganizationRequest): Promise<Organization> {
        const response = await this.getOrganizationRaw(requestParameters);
        return await response.value();
    }

    /**
     * List organizations
     */
    async listOrganizationRaw(requestParameters: ListOrganizationRequest): Promise<runtime.ApiResponse<ListUserOrganizations>> {
        if (requestParameters.max === null || requestParameters.max === undefined) {
            throw new runtime.RequiredError('max','Required parameter requestParameters.max was null or undefined when calling listOrganization.');
        }

        const queryParameters: any = {};

        if (requestParameters.max !== undefined) {
            queryParameters['max'] = requestParameters.max;
        }

        if (requestParameters.pageToken !== undefined) {
            queryParameters['pageToken'] = requestParameters.pageToken;
        }

        if (requestParameters.parent !== undefined) {
            queryParameters['parent'] = requestParameters.parent;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xUserUuid !== undefined && requestParameters.xUserUuid !== null) {
            headerParameters['X-User-Uuid'] = String(requestParameters.xUserUuid);
        }

        const response = await this.request({
            path: `/organizations`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => ListUserOrganizationsFromJSON(jsonValue));
    }

    /**
     * List organizations
     */
    async listOrganization(requestParameters: ListOrganizationRequest): Promise<ListUserOrganizations> {
        const response = await this.listOrganizationRaw(requestParameters);
        return await response.value();
    }

}
