/* tslint:disable */
/* eslint-disable */
/**
 * User account and session management
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LocalizedString,
    LocalizedStringFromJSON,
    LocalizedStringFromJSONTyped,
    LocalizedStringToJSON,
} from './';

/**
 * A request to create a new organization
 * @export
 * @interface CreateOrganizationPayload
 */
export interface CreateOrganizationPayload {
    /**
     * 
     * @type {LocalizedString}
     * @memberof CreateOrganizationPayload
     */
    name: LocalizedString;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateOrganizationPayload
     */
    equisoftConnectProfiles: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateOrganizationPayload
     */
    equisoftPlanProfiles: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizationPayload
     */
    parentUuid?: string | null;
}

export function CreateOrganizationPayloadFromJSON(json: any): CreateOrganizationPayload {
    return CreateOrganizationPayloadFromJSONTyped(json, false);
}

export function CreateOrganizationPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrganizationPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': LocalizedStringFromJSON(json['name']),
        'equisoftConnectProfiles': json['equisoftConnectProfiles'],
        'equisoftPlanProfiles': json['equisoftPlanProfiles'],
        'parentUuid': !exists(json, 'parentUuid') ? undefined : json['parentUuid'],
    };
}

export function CreateOrganizationPayloadToJSON(value?: CreateOrganizationPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': LocalizedStringToJSON(value.name),
        'equisoftConnectProfiles': value.equisoftConnectProfiles,
        'equisoftPlanProfiles': value.equisoftPlanProfiles,
        'parentUuid': value.parentUuid,
    };
}


