/* tslint:disable */
/* eslint-disable */
/**
 * User account and session management
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LocalizedString,
    LocalizedStringFromJSON,
    LocalizedStringFromJSONTyped,
    LocalizedStringToJSON,
} from './';

/**
 * A request to create or update an organization
 * @export
 * @interface CreateOrUpdateOrganizationPayload
 */
export interface CreateOrUpdateOrganizationPayload {
    /**
     * 
     * @type {LocalizedString}
     * @memberof CreateOrUpdateOrganizationPayload
     */
    name?: LocalizedString;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateOrUpdateOrganizationPayload
     */
    equisoftConnectProfiles?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateOrUpdateOrganizationPayload
     */
    equisoftPlanProfiles?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdateOrganizationPayload
     */
    parentUuid?: string | null;
}

export function CreateOrUpdateOrganizationPayloadFromJSON(json: any): CreateOrUpdateOrganizationPayload {
    return CreateOrUpdateOrganizationPayloadFromJSONTyped(json, false);
}

export function CreateOrUpdateOrganizationPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrUpdateOrganizationPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : LocalizedStringFromJSON(json['name']),
        'equisoftConnectProfiles': !exists(json, 'equisoftConnectProfiles') ? undefined : json['equisoftConnectProfiles'],
        'equisoftPlanProfiles': !exists(json, 'equisoftPlanProfiles') ? undefined : json['equisoftPlanProfiles'],
        'parentUuid': !exists(json, 'parentUuid') ? undefined : json['parentUuid'],
    };
}

export function CreateOrUpdateOrganizationPayloadToJSON(value?: CreateOrUpdateOrganizationPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': LocalizedStringToJSON(value.name),
        'equisoftConnectProfiles': value.equisoftConnectProfiles,
        'equisoftPlanProfiles': value.equisoftPlanProfiles,
        'parentUuid': value.parentUuid,
    };
}


