/* tslint:disable */
/* eslint-disable */
/**
 * User account and session management
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LocalizedString,
    LocalizedStringFromJSON,
    LocalizedStringFromJSONTyped,
    LocalizedStringToJSON,
} from './';

/**
 * create role schema
 * @export
 * @interface CreateRole
 */
export interface CreateRole {
    /**
     * 
     * @type {LocalizedString}
     * @memberof CreateRole
     */
    name: LocalizedString;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateRole
     */
    permissions: Array<string>;
}

export function CreateRoleFromJSON(json: any): CreateRole {
    return CreateRoleFromJSONTyped(json, false);
}

export function CreateRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRole {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': LocalizedStringFromJSON(json['name']),
        'permissions': json['permissions'],
    };
}

export function CreateRoleToJSON(value?: CreateRole | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': LocalizedStringToJSON(value.name),
        'permissions': value.permissions,
    };
}


