/* tslint:disable */
/* eslint-disable */
/**
 * User account and session management
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * States:
 * * `ENABLED` - Database is active.
 * * `DISABLED` - Access to this database is suspended.
 * * `DELETED` - Database is deleted.
 * * `MAINTENANCE` - Database is in maintenance, login temporarily suspended.
 * @export
 * @enum {string}
 */
export enum DatabaseState {
    ENABLED = 'ENABLED',
    DISABLED = 'DISABLED',
    DELETED = 'DELETED',
    MAINTENANCE = 'MAINTENANCE'
}

export function DatabaseStateFromJSON(json: any): DatabaseState {
    return DatabaseStateFromJSONTyped(json, false);
}

export function DatabaseStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatabaseState {
    return json as DatabaseState;
}

export function DatabaseStateToJSON(value?: DatabaseState | null): any {
    return value as any;
}

