/* tslint:disable */
/* eslint-disable */
/**
 * User account and session management
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnableEquisoftConnectPayloadSchema
 */
export interface EnableEquisoftConnectPayloadSchema {
    /**
     * When concurrent access exceeded, disable oldest sessions
     * @type {boolean}
     * @memberof EnableEquisoftConnectPayloadSchema
     */
    disableOldestSessions?: boolean | null;
}

export function EnableEquisoftConnectPayloadSchemaFromJSON(json: any): EnableEquisoftConnectPayloadSchema {
    return EnableEquisoftConnectPayloadSchemaFromJSONTyped(json, false);
}

export function EnableEquisoftConnectPayloadSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnableEquisoftConnectPayloadSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'disableOldestSessions': !exists(json, 'disableOldestSessions') ? undefined : json['disableOldestSessions'],
    };
}

export function EnableEquisoftConnectPayloadSchemaToJSON(value?: EnableEquisoftConnectPayloadSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'disableOldestSessions': value.disableOldestSessions,
    };
}


