/* tslint:disable */
/* eslint-disable */
/**
 * User account and session management
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Parameters needed to impersonanted a user for a user session
 * @export
 * @interface ImpersonatePayload
 */
export interface ImpersonatePayload {
    /**
     * Globally unique identifier.
     * @type {string}
     * @memberof ImpersonatePayload
     */
    userUuid: string;
}

export function ImpersonatePayloadFromJSON(json: any): ImpersonatePayload {
    return ImpersonatePayloadFromJSONTyped(json, false);
}

export function ImpersonatePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImpersonatePayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userUuid': json['userUuid'],
    };
}

export function ImpersonatePayloadToJSON(value?: ImpersonatePayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userUuid': value.userUuid,
    };
}


