/* tslint:disable */
/* eslint-disable */
/**
 * User account and session management
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LocalizedString,
    LocalizedStringFromJSON,
    LocalizedStringFromJSONTyped,
    LocalizedStringToJSON,
    OrganizationPathElement,
    OrganizationPathElementFromJSON,
    OrganizationPathElementFromJSONTyped,
    OrganizationPathElementToJSON,
} from './';

/**
 * 
 * @export
 * @interface ListOrganizationElement
 */
export interface ListOrganizationElement {
    /**
     * 
     * @type {string}
     * @memberof ListOrganizationElement
     */
    uuid: string;
    /**
     * 
     * @type {LocalizedString}
     * @memberof ListOrganizationElement
     */
    name: LocalizedString;
    /**
     * 
     * @type {string}
     * @memberof ListOrganizationElement
     */
    parentUuid?: string | null;
    /**
     * 
     * @type {Array<OrganizationPathElement>}
     * @memberof ListOrganizationElement
     */
    path: Array<OrganizationPathElement>;
}

export function ListOrganizationElementFromJSON(json: any): ListOrganizationElement {
    return ListOrganizationElementFromJSONTyped(json, false);
}

export function ListOrganizationElementFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOrganizationElement {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'name': LocalizedStringFromJSON(json['name']),
        'parentUuid': !exists(json, 'parentUuid') ? undefined : json['parentUuid'],
        'path': ((json['path'] as Array<any>).map(OrganizationPathElementFromJSON)),
    };
}

export function ListOrganizationElementToJSON(value?: ListOrganizationElement | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uuid': value.uuid,
        'name': LocalizedStringToJSON(value.name),
        'parentUuid': value.parentUuid,
        'path': ((value.path as Array<any>).map(OrganizationPathElementToJSON)),
    };
}


