/* tslint:disable */
/* eslint-disable */
/**
 * User account and session management
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ListOrganizationElement,
    ListOrganizationElementFromJSON,
    ListOrganizationElementFromJSONTyped,
    ListOrganizationElementToJSON,
} from './';

/**
 * 
 * @export
 * @interface ListUserOrganizations
 */
export interface ListUserOrganizations {
    /**
     * 
     * @type {Array<ListOrganizationElement>}
     * @memberof ListUserOrganizations
     */
    organizations: Array<ListOrganizationElement>;
}

export function ListUserOrganizationsFromJSON(json: any): ListUserOrganizations {
    return ListUserOrganizationsFromJSONTyped(json, false);
}

export function ListUserOrganizationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListUserOrganizations {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'organizations': ((json['organizations'] as Array<any>).map(ListOrganizationElementFromJSON)),
    };
}

export function ListUserOrganizationsToJSON(value?: ListUserOrganizations | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'organizations': ((value.organizations as Array<any>).map(ListOrganizationElementToJSON)),
    };
}


