/* tslint:disable */
/* eslint-disable */
/**
 * User account and session management
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LocalizedString
 */
export interface LocalizedString {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof LocalizedString
     */
    values?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof LocalizedString
     */
    defaultLocale?: string;
}

export function LocalizedStringFromJSON(json: any): LocalizedString {
    return LocalizedStringFromJSONTyped(json, false);
}

export function LocalizedStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalizedString {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'values': !exists(json, 'values') ? undefined : json['values'],
        'defaultLocale': !exists(json, 'defaultLocale') ? undefined : json['defaultLocale'],
    };
}

export function LocalizedStringToJSON(value?: LocalizedString | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'values': value.values,
        'defaultLocale': value.defaultLocale,
    };
}


