/* tslint:disable */
/* eslint-disable */
/**
 * User account and session management
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Information about the created organization
 * @export
 * @interface OrganizationCreated
 */
export interface OrganizationCreated {
    /**
     * 
     * @type {string}
     * @memberof OrganizationCreated
     */
    uuid: string;
}

export function OrganizationCreatedFromJSON(json: any): OrganizationCreated {
    return OrganizationCreatedFromJSONTyped(json, false);
}

export function OrganizationCreatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationCreated {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
    };
}

export function OrganizationCreatedToJSON(value?: OrganizationCreated | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uuid': value.uuid,
    };
}


