/* tslint:disable */
/* eslint-disable */
/**
 * User account and session management
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LocalizedString,
    LocalizedStringFromJSON,
    LocalizedStringFromJSONTyped,
    LocalizedStringToJSON,
} from './';

/**
 * 
 * @export
 * @interface OrganizationPathElement
 */
export interface OrganizationPathElement {
    /**
     * 
     * @type {LocalizedString}
     * @memberof OrganizationPathElement
     */
    name: LocalizedString;
    /**
     * 
     * @type {string}
     * @memberof OrganizationPathElement
     */
    uuid: string;
}

export function OrganizationPathElementFromJSON(json: any): OrganizationPathElement {
    return OrganizationPathElementFromJSONTyped(json, false);
}

export function OrganizationPathElementFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationPathElement {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': LocalizedStringFromJSON(json['name']),
        'uuid': json['uuid'],
    };
}

export function OrganizationPathElementToJSON(value?: OrganizationPathElement | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': LocalizedStringToJSON(value.name),
        'uuid': value.uuid,
    };
}


