/* tslint:disable */
/* eslint-disable */
/**
 * User account and session management
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Information about the created permission
 * @export
 * @interface PermissionCreated
 */
export interface PermissionCreated {
    /**
     * 
     * @type {string}
     * @memberof PermissionCreated
     */
    code?: string;
}

export function PermissionCreatedFromJSON(json: any): PermissionCreated {
    return PermissionCreatedFromJSONTyped(json, false);
}

export function PermissionCreatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionCreated {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
    };
}

export function PermissionCreatedToJSON(value?: PermissionCreated | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
    };
}


