/* tslint:disable */
/* eslint-disable */
/**
 * User account and session management
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LocalizedString,
    LocalizedStringFromJSON,
    LocalizedStringFromJSONTyped,
    LocalizedStringToJSON,
} from './';

/**
 * created role schema
 * @export
 * @interface RoleCreated
 */
export interface RoleCreated {
    /**
     * 
     * @type {string}
     * @memberof RoleCreated
     */
    uuid?: string;
    /**
     * 
     * @type {LocalizedString}
     * @memberof RoleCreated
     */
    name?: LocalizedString;
    /**
     * 
     * @type {Array<string>}
     * @memberof RoleCreated
     */
    permissions?: Array<string>;
}

export function RoleCreatedFromJSON(json: any): RoleCreated {
    return RoleCreatedFromJSONTyped(json, false);
}

export function RoleCreatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleCreated {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
        'name': !exists(json, 'name') ? undefined : LocalizedStringFromJSON(json['name']),
        'permissions': !exists(json, 'permissions') ? undefined : json['permissions'],
    };
}

export function RoleCreatedToJSON(value?: RoleCreated | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uuid': value.uuid,
        'name': LocalizedStringToJSON(value.name),
        'permissions': value.permissions,
    };
}


