/* tslint:disable */
/* eslint-disable */
/**
 * User account and session management
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ServiceName {
    EQUISOFT_CONNECT = 'EQUISOFT_CONNECT',
    EQUISOFT_PLAN = 'EQUISOFT_PLAN',
    EQUISOFT_ANALYZE_FOR_ADVISORS = 'EQUISOFT_ANALYZE_FOR_ADVISORS',
    CPANEL = 'CPANEL'
}

export function ServiceNameFromJSON(json: any): ServiceName {
    return ServiceNameFromJSONTyped(json, false);
}

export function ServiceNameFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceName {
    return json as ServiceName;
}

export function ServiceNameToJSON(value?: ServiceName | null): any {
    return value as any;
}

