/* tslint:disable */
/* eslint-disable */
/**
 * User account and session management
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * UUID response for a service account
 * @export
 * @interface ServiceAccountUuidSchema
 */
export interface ServiceAccountUuidSchema {
    /**
     * 
     * @type {string}
     * @memberof ServiceAccountUuidSchema
     */
    uuid?: string;
}

export function ServiceAccountUuidSchemaFromJSON(json: any): ServiceAccountUuidSchema {
    return ServiceAccountUuidSchemaFromJSONTyped(json, false);
}

export function ServiceAccountUuidSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceAccountUuidSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
    };
}

export function ServiceAccountUuidSchemaToJSON(value?: ServiceAccountUuidSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uuid': value.uuid,
    };
}


