/* tslint:disable */
/* eslint-disable */
/**
 * User account and session management
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Information about the created service account
 * @export
 * @interface ServiceAccountCreatedSchema
 */
export interface ServiceAccountCreatedSchema {
    /**
     * 
     * @type {string}
     * @memberof ServiceAccountCreatedSchema
     */
    uuid?: string;
}

export function ServiceAccountCreatedSchemaFromJSON(json: any): ServiceAccountCreatedSchema {
    return ServiceAccountCreatedSchemaFromJSONTyped(json, false);
}

export function ServiceAccountCreatedSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceAccountCreatedSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
    };
}

export function ServiceAccountCreatedSchemaToJSON(value?: ServiceAccountCreatedSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uuid': value.uuid,
    };
}


