/* tslint:disable */
/* eslint-disable */
/**
 * User account and session management
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ServiceAccountStatus {
    ENABLED = 'ENABLED',
    DISABLED = 'DISABLED',
    DELETED = 'DELETED'
}

export function ServiceAccountStatusFromJSON(json: any): ServiceAccountStatus {
    return ServiceAccountStatusFromJSONTyped(json, false);
}

export function ServiceAccountStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceAccountStatus {
    return json as ServiceAccountStatus;
}

export function ServiceAccountStatusToJSON(value?: ServiceAccountStatus | null): any {
    return value as any;
}

