/* tslint:disable */
/* eslint-disable */
/**
 * User account and session management
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SessionState,
    SessionStateFromJSON,
    SessionStateFromJSONTyped,
    SessionStateToJSON,
    SsoProvider,
    SsoProviderFromJSON,
    SsoProviderFromJSONTyped,
    SsoProviderToJSON,
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './';

/**
 * 
 * @export
 * @interface Session
 */
export interface Session {
    /**
     * Globally unique identifier.
     * @type {string}
     * @memberof Session
     */
    sessionId?: string;
    /**
     * 
     * @type {SessionState}
     * @memberof Session
     */
    state?: SessionState;
    /**
     * 
     * @type {Date}
     * @memberof Session
     */
    created?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Session
     */
    expire?: Date;
    /**
     * 
     * @type {User}
     * @memberof Session
     */
    user?: User;
    /**
     * 
     * @type {User}
     * @memberof Session
     */
    actor?: User;
    /**
     * 
     * @type {SsoProvider}
     * @memberof Session
     */
    sso?: SsoProvider;
    /**
     * Session is enabled for Equisoft/Connect and is accounted for concurrent access.
     * @type {boolean}
     * @memberof Session
     */
    enabledForEquisoftConnect?: boolean;
    /**
     * Indicate that the session is initiated from a mobile device.
     * @type {boolean}
     * @memberof Session
     */
    mobile?: boolean;
}

export function SessionFromJSON(json: any): Session {
    return SessionFromJSONTyped(json, false);
}

export function SessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Session {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sessionId': !exists(json, 'sessionId') ? undefined : json['sessionId'],
        'state': !exists(json, 'state') ? undefined : SessionStateFromJSON(json['state']),
        'created': !exists(json, 'created') ? undefined : (new Date(json['created'])),
        'expire': !exists(json, 'expire') ? undefined : (new Date(json['expire'])),
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
        'actor': !exists(json, 'actor') ? undefined : UserFromJSON(json['actor']),
        'sso': !exists(json, 'sso') ? undefined : SsoProviderFromJSON(json['sso']),
        'enabledForEquisoftConnect': !exists(json, 'enabledForEquisoftConnect') ? undefined : json['enabledForEquisoftConnect'],
        'mobile': !exists(json, 'mobile') ? undefined : json['mobile'],
    };
}

export function SessionToJSON(value?: Session | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sessionId': value.sessionId,
        'state': SessionStateToJSON(value.state),
        'created': value.created === undefined ? undefined : (value.created.toISOString()),
        'expire': value.expire === undefined ? undefined : (value.expire.toISOString()),
        'user': UserToJSON(value.user),
        'actor': UserToJSON(value.actor),
        'sso': SsoProviderToJSON(value.sso),
        'enabledForEquisoftConnect': value.enabledForEquisoftConnect,
        'mobile': value.mobile,
    };
}


