/* tslint:disable */
/* eslint-disable */
/**
 * User account and session management
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Details related to the SSO provider user to create this session.
 * @export
 * @interface SsoProvider
 */
export interface SsoProvider {
    /**
     * SSO Provider who initiated the single sign on.
     * @type {string}
     * @memberof SsoProvider
     */
    provider?: string;
    /**
     * External identifier the user used to login with the SSO provider.
     * @type {string}
     * @memberof SsoProvider
     */
    identifier?: string;
}

export function SsoProviderFromJSON(json: any): SsoProvider {
    return SsoProviderFromJSONTyped(json, false);
}

export function SsoProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): SsoProvider {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'provider': !exists(json, 'provider') ? undefined : json['provider'],
        'identifier': !exists(json, 'identifier') ? undefined : json['identifier'],
    };
}

export function SsoProviderToJSON(value?: SsoProvider | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'provider': value.provider,
        'identifier': value.identifier,
    };
}


