/* tslint:disable */
/* eslint-disable */
/**
 * User account and session management
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SsoToken
 */
export interface SsoToken {
    /**
     * String that uniquely identify a sso token for a given session.
     * @type {string}
     * @memberof SsoToken
     */
    id: string;
    /**
     * Token value returned as stored. There is no double-encoding.
     * @type {string}
     * @memberof SsoToken
     */
    value: string;
}

export function SsoTokenFromJSON(json: any): SsoToken {
    return SsoTokenFromJSONTyped(json, false);
}

export function SsoTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): SsoToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'value': json['value'],
    };
}

export function SsoTokenToJSON(value?: SsoToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'value': value.value,
    };
}


