/* tslint:disable */
/* eslint-disable */
/**
 * User account and session management
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LocalizedString,
    LocalizedStringFromJSON,
    LocalizedStringFromJSONTyped,
    LocalizedStringToJSON,
} from './';

/**
 * 
 * @export
 * @interface UserAccountRole
 */
export interface UserAccountRole {
    /**
     * 
     * @type {string}
     * @memberof UserAccountRole
     */
    uuid: string;
    /**
     * 
     * @type {LocalizedString}
     * @memberof UserAccountRole
     */
    name: LocalizedString;
}

export function UserAccountRoleFromJSON(json: any): UserAccountRole {
    return UserAccountRoleFromJSONTyped(json, false);
}

export function UserAccountRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAccountRole {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'name': LocalizedStringFromJSON(json['name']),
    };
}

export function UserAccountRoleToJSON(value?: UserAccountRole | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uuid': value.uuid,
        'name': LocalizedStringToJSON(value.name),
    };
}


