/* tslint:disable */
/* eslint-disable */
/**
 * User account and session management
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * States: * `DELETED` - User is soft deleted or archived. * `DISABLED` - Temporarily denied login. * `ENABLED` - Allowed to login. 
 * @export
 * @enum {string}
 */
export enum UserState {
    DELETED = 'DELETED',
    DISABLED = 'DISABLED',
    ENABLED = 'ENABLED'
}

export function UserStateFromJSON(json: any): UserState {
    return UserStateFromJSONTyped(json, false);
}

export function UserStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserState {
    return json as UserState;
}

export function UserStateToJSON(value?: UserState | null): any {
    return value as any;
}

