/* tslint:disable */
/* eslint-disable */
/**
 * User account and session management
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * States:
 * * `ACCEPTED` - User agreement and term of use accepted by user.
 * * `REQUESTED` - User has yet to approve user agreements.
 * @export
 * @enum {string}
 */
export enum UserAgreementState {
    ACCEPTED = 'ACCEPTED',
    REQUESTED = 'REQUESTED'
}

export function UserAgreementStateFromJSON(json: any): UserAgreementState {
    return UserAgreementStateFromJSONTyped(json, false);
}

export function UserAgreementStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAgreementState {
    return json as UserAgreementState;
}

export function UserAgreementStateToJSON(value?: UserAgreementState | null): any {
    return value as any;
}

