/* tslint:disable */
/* eslint-disable */
/**
 * User account and session management
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The list of UUIDs that matched the search.
 * @export
 * @interface UserAccountSearchResult
 */
export interface UserAccountSearchResult {
    /**
     * 
     * @type {string}
     * @memberof UserAccountSearchResult
     */
    uuid: string;
}

export function UserAccountSearchResultFromJSON(json: any): UserAccountSearchResult {
    return UserAccountSearchResultFromJSONTyped(json, false);
}

export function UserAccountSearchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAccountSearchResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
    };
}

export function UserAccountSearchResultToJSON(value?: UserAccountSearchResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uuid': value.uuid,
    };
}


